### ISSUE TITLE
Trying to install package in react native causes build failure

### ISSUE THREAD

**Issue by jrereyi2000** [getbouncer/react-native-cardscan#129]
In the integration guide, the steps for adding the package include two separate things that are causing me issues. 

In the PodFile, I add 

  pod 'CardScan'
  pod 'react-native-cardscan', :path => '../node_modules/react-native-cardscan/react-native-cardscan.podspec'

after installing the package. However, when running pod install after, I get an error that 

There are multiple dependencies with different sources for `react-native-cardscan` in `Podfile`:

- react-native-cardscan (from `../node_modules/react-native-cardscan`)
- react-native-cardscan (from `../node_modules/react-native-cardscan/react-native-cardscan.podspec`)

If I remove those lines from the PodFile, I can pod install the rest of my pods again, but building fails due to the 2nd error. 

2nd Error:
In AppDelegate.m, I add

[ScanViewController configureWithApiKey:@"<your_api_key_here>"];

To didFinishLaunchingWithOptions, however, I get two errors:

"Unknown receiver 'ScanViewController'; did you mean 'UIViewController'?"
&
No known class method for selector 'configureWithApiKey:'

which prevents me from building.

Are there any fixes for this?

**Comment by webforuse** [comment]
confirmed
Build (release) Archive get error
Run on device is ok

**Comment by jaimepark-stripe** [comment]
Hello @jrereyi2000 @webforuse!
Thank you for bringing this up. I will try to reproduce these errors right now. 

If I am understanding your issues correctly,
@jrereyi2000: You're having a build issue with the Podfile.
@webforuse : You can build your project but can't archive.

**Comment by jaimepark-stripe** [comment]
@jrereyi2000  @webforuse 
I apologize for the late response. This issue is top priority and I will regular post updates. Working on it now.

**Comment by jaimepark-stripe** [comment]
@jrereyi2000  
I was able to properly install and build my project with the Podfile specs you sent me. I was also to configure my apiKey as you addressed with your second error. We may need to dig a bit deeper. 

Could you send me your `full Podfile`, `XCode version`, `react-native version`, and `npm version` so I can try my best to replicate your build environment.

**Comment by jaimepark-stripe** [comment]
@webforuse 
I was also able build + archive a release version of my example project. Could you provide me with a stack trace?

**Comment by eduardopelitti** [comment]
Hi @jaimepark-stripe, 

I was getting the same issue when trying to follow the installation steps from scratch on an existing project. 

After following the installation steps, I got an error while running `pod install`:

```
[!] There are multiple dependencies with different sources for `react-native-cardscan` in `Podfile`:

- react-native-cardscan (from `../node_modules/react-native-cardscan`)
- react-native-cardscan (from `../node_modules/react-native-cardscan/react-native-cardscan.podspec`)
```

**[Find below my system specs and original Podfile]**


I was able to solve this issue by modifying the Podfile like this:
```
  pod 'CardScan'
  pod 'react-native-cardscan', :path => '../node_modules/react-native-cardscan'
```

After which I got a new error:

```
[!] CocoaPods could not find compatible versions for pod "CardScan":
  In Podfile:
    CardScan

    react-native-cardscan (from `../node_modules/react-native-cardscan`) was resolved to 1.1.30, which depends on
      CardScan (~> 2.0.9)

Specs satisfying the `CardScan, CardScan (~> 2.0.9)` dependency were found, but they required a higher minimum deployment target.
```

Which I was in turn able to resolve by bumping the `platform :ios, '10.0'` to `platform :ios, '12.0'`.

After these changes the project built.

I think that perhaps the part that @jrereyi2000 mentions in the `AppDelegate.m` could be due to a missing import statement for CardScan:

```
@import CardScan;
 ```

But this is just a guess based on my own experience following the installation guides for the first time.


----------------------------------------------------------------------

This is my setup:

```
System:
    OS: macOS 11.2.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 86.13 MB / 16.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 14.15.1 - ~/.nvm/versions/node/v14.15.1/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.20.1 - ~/ank-mobile/node_modules/.bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.10.1 - /Users/eduardopelitti/.gem/ruby/2.6.0/bin/pod
  SDKs:
    iOS SDK:
      Platforms: iOS 14.4, DriverKit 20.2, macOS 11.1, tvOS 14.3, watchOS 7.2
    Android SDK:
      API Levels: 28, 29, 30
      Build Tools: 28.0.3, 29.0.2, 29.0.3, 30.0.3
      System Images: android-30 | Google APIs Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.1 AI-201.8743.12.41.7042882
    Xcode: 12.4/12D4e - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_282 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.1 => 17.0.1 
    react-native: 0.64.2 => 0.64.2 
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

And my original Podfile is:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

# "SKIP_FLIPPER_INSTALLATION" environment variable is defined in CI
def should_install_flipper()
  return ENV["SKIP_FLIPPER_INSTALLATION"].nil?
end

target '****' do
  config = use_native_modules!

  # Pods for ****
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  # your other libraries will follow here!
  ...
  pod 'CardScan'
  pod 'react-native-cardscan', :path => '../node_modules/react-native-cardscan/react-native-cardscan.podspec'
  ...

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  install_flipper = should_install_flipper()

  if install_flipper
    use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  end

  post_install do |installer|
    # Improve the Pods project setting to match with the ones we want to have for the project
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end
    end
    react_native_post_install(installer)
  end
end
```

Resulting Podfile that succeeds installing pods for the project:

```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '12.0'

# "SKIP_FLIPPER_INSTALLATION" environment variable is defined in CI
def should_install_flipper()
  return ENV["SKIP_FLIPPER_INSTALLATION"].nil?
end

target '****' do
  config = use_native_modules!

  # Pods for ****
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods
    :hermes_enabled => true
  )

  # your other libraries will follow here!
  ...
  pod 'CardScan'
  pod 'react-native-cardscan', :path => '../node_modules/react-native-cardscan'
  ...

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.

  install_flipper = should_install_flipper()

  if install_flipper
    use_flipper!('Flipper' => '0.75.1', 'Flipper-Folly' => '2.5.3', 'Flipper-RSocket' => '1.3.1')
  end

  post_install do |installer|
    # Improve the Pods project setting to match with the ones we want to have for the project
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'RCT_ENABLE_INSPECTOR=0'
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'ENABLE_PACKAGER_CONNECTION=0'
      end
    end
    react_native_post_install(installer)
  end
end
```

BTW, on Android, after following the install steps I had to upgrade the Kotlin version as well, to support a minimum of `1.3.70`:

```
classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.70"
``` 

This in order to resolve an issue with `kotlin/coroutines/AbstractCoroutineContextKey java.lang.NoClassDefFoundError`. After that the project built and the implementation was successful.

I hope this helps! Let me know if you need any more information or additional debugging.

**Comment by jaimepark-stripe** [comment]
Hello @eduardopelitti!
Wow thank you for all the detailed informations!! Let me follow your steps and reproduce on my end. Ill get back to you ASA{ once I have more insight.

**Comment by kingst-stripe** [comment]
Sorry about the delay here and thank you for the info. We updated our integration docs and the example app to reflect the excellent suggestions in this issue. Please let us know if you continue to have problems and thank you again for helping out!
