### ISSUE TITLE
react-native issue

### ISSUE THREAD

**Issue by ant000205** [getbouncer/react-native-cardscan#13]
error: cannot find symbol
     RNCardScanModule.apiKey = "";
     ^
  symbol:   variable RNCardScanModule
  location: class MainApplication

**Comment by awushensky** [comment]
Sorry! looks like the documentation was wrong. It should be `RNCardscanModule.apiKey`. I've updated the documentation to reflect this.

**Comment by awushensky** [comment]
I'm closing this as resolved. Please feel free to re-open if the issue reoccurs.
