### ISSUE TITLE
Value of card expiry month, year

### ISSUE THREAD

**Issue by PhotonUser0701** [getbouncer/react-native-cardscan#150]
Not getting values of expiry month, year from the library. Its showing null value
![Screenshot 2021-09-17 at 5 06 27 PM](https://user-images.githubusercontent.com/90908017/133776251-b5b0941d-c2c4-4444-b90c-be6ae81b5de3.png)
.

**Comment by kingst-stripe** [comment]
When we complete a scan we always return the card number, but these other fields are all best effort and aren't always detected.
