### ISSUE TITLE
iOS Build issue package not recognised as being installed

### ISSUE THREAD

**Issue by RobertBMerriman** [getbouncer/react-native-cardscan#157]
Hi all!

I have an issue building the iOS project as you can see below:

<img width="291" alt="Screenshot 2021-10-27 at 3 15 18 pm" src="https://user-images.githubusercontent.com/16168932/139084432-4fdfbe2f-1fdc-4fa8-8312-8662ccf5bbec.png">

<img width="667" alt="Screenshot 2021-10-27 at 3 15 43 pm" src="https://user-images.githubusercontent.com/16168932/139084444-9900255e-289a-4907-92e7-accc9f7a2a91.png">

`@import CardScan;` doesn't give me an error but I get no autocomplete for it either:

<img width="487" alt="Screenshot 2021-10-27 at 3 15 59 pm" src="https://user-images.githubusercontent.com/16168932/139084499-efdffb5d-88c6-40e0-ac92-a08ef8f240df.png">

I have confirmed the pods are installed as you can see here, and this setup works for Android:

<img width="737" alt="pods confirmed installed" src="https://user-images.githubusercontent.com/16168932/139084815-acfb8756-5e0f-4eec-8458-6f0a9d7178a0.png">

I suspect this issue derives from using unimodules to manage pods however the Podfile.lock contains the correct pods as far as I can see:

`ios/Podfile`:
```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

target 'Glide' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'GlideTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
         end
      end
    end
  end
end

```

`ios/Podfile.lock` (relevant sections):
```
PODS:
...
  - CardScan (2.0.9)
...
  - react-native-cardscan (1.1.30):
    - CardScan (~> 2.0.9)
    - React
...
DEPENDENCIES:
...
  - react-native-cardscan (from `../node_modules/react-native-cardscan`)
...
SPEC REPOS:
  trunk:
...
       - CardScan
...
EXTERNAL SOURCES:
...
  react-native-cardscan:
    :path: "../node_modules/react-native-cardscan"
...

```

I hope this is enough info for you to understand my issue, thanks for taking a look

**Comment by jaimepark-stripe** [comment]
Hello @RobertBMerriman!
Thank you for bringing this up. Can you quickly try setting the key with `SimpleScanViewController` and see what the results are?

**Comment by RobertBMerriman** [comment]
@jaimepark-stripe Hi Jaime thanks for looking I've just tried what you suggested and I'm still getting the same issue
<img width="659" alt="Screenshot 2021-10-29 at 1 21 46 pm" src="https://user-images.githubusercontent.com/16168932/139433493-4b8ab3ca-a5f7-4f73-8671-90e9ecda752c.png">

**Comment by jaimepark-stripe** [comment]
oh no! Let me take a deeper look into this.

**Comment by RobertBMerriman** [comment]
Hi @jaimepark-stripe I can see this timezones are making this drag on so I will online late today (for me anyway! early for you I think) and hopefully we can reach a resolution 😊

**Comment by jaimepark-stripe** [comment]
Hello @RobertBMerriman,
@kingst-stripe will be able to help you out with this issue!

**Comment by jaimepark-stripe** [comment]
Hello @RobertBMerriman!
I apologize for the delayed response. I am curious as to how the pods `CardScan` and `react-native-cardscan` are in your Podfile.lock but not in the Podfile.  Your Podfile should look something like this:
```
target 'Your App' do
  ...
  pod 'CardScan'
  pod 'react-native-cardscan', :path => '../node_modules/react-native-cardscan'
end
```
Have you tried adding the pods above to your Podfile + `pod deintegrate && pod install`?
While you try that, I will copy your Podfile and try to replicate this error on my end!

Also: Can you tell me why you are using `unimodules`? https://docs.expo.dev/bare/installing-unimodules/ 

Thank you and I hope to hear from you soon!

**Comment by RobertBMerriman** [comment]
Hi @jaimepark-stripe 

I have tried adding the pods manually and as you suggested but as far as I can see it makes no difference as they are installed anyway. I believe this is done via the bottom section or the requires.
I have inherited this from another developer who has now left so I'm not totally sure (I can investigate if necessary) however bottom line the pods do install. I will leave the pod declarations in the file just to make sure.

And to answer the `unimodules` question this is due to inheriting the project, I can also look into upgrading to the expo version too

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'

platform :ios, '12.0'

target 'Glide' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => false
  )

  target 'GlideTests' do
    inherit! :complete
  end
  
  pod 'CardScan'
  pod 'react-native-cardscan', :path => '../node_modules/react-native-cardscan'

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
         if config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'].to_f < 9.0
           config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
         end
      end
    end
  end
end

```

**Comment by RobertBMerriman** [comment]
@jaimepark-stripe If you have any next steps you recommend me trying in the meantime please let me know

**Comment by kingst-stripe** [comment]
@RobertBMerriman looking at your code snippet it looks like there is a `#ifdef FB_SONARKIT_ENABLED` defined that the import for `CardScan` is guarded by, is it possible that that macro isn't defined and `CardScan` isn't getting imported? Maybe try moving the import to above the `#ifdef` line?

**Comment by RobertBMerriman** [comment]
@kingst-stripe You're on to something! While it doesn't work it has given me an error for the first time

<img width="716" alt="Screenshot 2021-11-05 at 10 43 45 am" src="https://user-images.githubusercontent.com/16168932/140498732-9ca7dc48-dc71-4486-bc4e-7f634e753a5b.png">

**Comment by RobertBMerriman** [comment]
I can confirm the pod has installed as when I run `pod deintegrate && pod install` I see both pods install:

<img width="413" alt="Screenshot 2021-11-05 at 10 47 33 am" src="https://user-images.githubusercontent.com/16168932/140499335-206b286d-fbb0-41f5-b1f0-511af608746b.png">

<img width="705" alt="Screenshot 2021-11-05 at 10 47 22 am" src="https://user-images.githubusercontent.com/16168932/140499327-896babf5-18a4-40ed-9d27-e831974d6570.png">

I can only think that there must be some missing config?

**Comment by RobertBMerriman** [comment]
@kingst-stripe False alarm it builds!! Thanks so much for that I've been stumped for so long I'm glad it turned out to be something that simple to fix :)

<img width="311" alt="Screenshot 2021-11-05 at 10 52 38 am" src="https://user-images.githubusercontent.com/16168932/140499854-a8169f37-359b-4ba8-92fe-7c36ec25e7d9.png">
(I cheered when I saw that --^)

**Comment by kingst-stripe** [comment]
Great, glad that we were able to help, closing this issue
