### ISSUE TITLE
Exposing CreditCardUtils

### ISSUE THREAD

**Issue by billkim84** [getbouncer/react-native-cardscan#158]
I'd like to add regional issuers but I don't know how to do it. 

How can we use CreditCardUtils? 

in iOS, we can use like this 
`CreditCardUtils.prefixesRegional += ["123456"]`

**Comment by awush-stripe** [comment]
hi @billkim84 , this is supported through the `CardIssuer.Custom` object. Here's a doc that outlines how to change this in android: https://docs.getbouncer.com/bouncer-scan/verifying-high-risk-cards/android-integration-guide/card-support

Please feel free to re-open this issue if this does not answer your question.
