### ISSUE TITLE
Still requires API Key setup

### ISSUE THREAD

**Issue by anhquan291** [getbouncer/react-native-cardscan#164]
Hi Bouncer team,

Thanks for this amazing library. However, I cannot make it work since the SDK on android still requires key setup (but the latest announcement said that api key are no longer required) 

Any help please? Thank a lot.

**Comment by rogerchang** [comment]
I was able to get it to work by using this as the key
`abcdefghijklmnopqrstuvwxyz123456`
It just needs to be 32 characters long.
