### ISSUE TITLE
CVC number not scanned

### ISSUE THREAD

**Issue by SatalBill** [getbouncer/react-native-cardscan#84]
I used this package for credit card scanning. 
As well known, there are 16 digits and expiry date in the front side of credit card, and there is CVC number(3 digits) in the back side of credit card.
So after I scan front side, I had to flip card to scan CVC number.
I followed sample code provided by this package.

const { action, scanId, payload, canceledReason } = await Cardscan.scan();
if (action === 'scanned') {
      var issuer = payload.issuer || '??';
      if (issuer === 'MasterCard') {
        issuer = 'master-card';
      } else if (issuer === 'American Express') {
        issuer = 'american-express';
      } else {
        issuer = issuer.toLowerCase();
      }
      setCard({
        number: payload.number,
        expiryDay: payload.expiryDay || '',
        expiryMonth: payload.expiryMonth || '??',
        expiryYear: payload.expiryYear || '??',
        issuer: issuer,
        cvc: payload.cvc || '??',     //----------------------------------->>>>>    Here !    <<<<<----------------
        cardholderName: payload.cardholderName || '??',
        error: payload.error || ''
      });
    }

As you can see, when I scan front side of credit card, cvc value comes with all other data from payload.
So in order to scan CVC, I called another function with almost same content

if(cvc == '??'){
      setCard({
        ...this.state.card,
        cvc: payload.cvc
      });
}

But I couldn't get any cvc data.
Those are images that I used for scanning purpose.
![Attachment_1607535080](https://user-images.githubusercontent.com/54341942/101830371-5f3a5880-3b6f-11eb-9463-4858d69814fd.png)

![Attachment_1607534711 (2)](https://user-images.githubusercontent.com/54341942/101830418-70836500-3b6f-11eb-8eaf-eff8ebafbd49.jpeg)

How to scan cvc?

**Comment by awushensky** [comment]
Hey @SatalBill , we don't yet support CVC scanning. It's a feature we're planning to add and have some placeholders for, but it's not yet part of our library.

**Comment by SatalBill** [comment]
Thank you for your kind answer. Actually I spent almost 3 days to scan CVC number.
Then could you please kindly let me know which package can scan CVC number?
I have already tried "react-native-awesome-card-io", but not work at all even 16 digits and exp date.
Which module must be used to scan CVC? 
Or is it impossible to scan CVC in React Native?

**Comment by awushensky** [comment]
Unfortunately I don't know much about other react native libraries that scan cards, this one is developed by Bouncer Technologies; the other libraries have other maintainers.

Sorry I don't have a better answer for you!

**Comment by SatalBill** [comment]
No problem. I appreciate your attitude in attending developers. Thank you so much even though I don't get enough information.
Hope it can scan CVC also in a short time.

**Comment by SatalBill** [comment]
When I use this module, the blue border appears through the rectangle border.
Is it possible to remove it? Or is there any way to scan more fast?

**Comment by awushensky** [comment]
The blue border indicates the progress of the scan. You can speed up the processing time after the scan by turning off name and expiry extraction. the speed of the scan depends on how easy it is to read the card and how fast the device is. newer devices will scan faster than older devices, and cards with very clear numbers will scan faster than cards with difficult to read numbers.

**Comment by SatalBill** [comment]
Thank you very much

**Comment by Nikhil14311** [comment]
Printed numbers in the card right. That type of cards only get reading. For normal numbers won't reading. Please give me response as soon as possible.  Please reply me through mail karanamnikhil00@gmail.com
